# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db157e58772cf5262be1ae7b1db984f18f5a931e2a7bd2a4cbadd064028824ec5ed998a79d9c334146800f14db6f41dd73230c3ff7afaaa158a54bc6502e824

test:
  secret_key_base: 58d3471a1422cc27c204998b47c6343743a6fc77b76dd6ff64e172a50b7c888fa7d4ed7473d7b848e29a7dab8d0ab737459969dae264b3fee0f982e8e0aff7da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
